<div class="footer">
    <table>
        <tr>
            <td>Generated by E-Keuangan MAN 2 Surakarta on {{ $generatedAt->format('Y-m-d H:i:s') }}</td>
            <td class="center">Document ID: {{ $documentId }}</td>
            <td class="right">Page {{ $pageNumber ?? 1 }} of {{ $totalPages ?? 1 }}</td>
        </tr>
    </table>
</div>
