@php
    $invoices = isset($invoices) ? collect($invoices) : collect([$invoice]);
    $titleInvoice = $invoices->first();
@endphp

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <title>Tagihan {{ $titleInvoice?->invoice_no ?? 'Invoice' }}</title>
    @include('prints.partials.invoice-styles')
</head>
<body>
    @foreach ($invoices as $invoice)
    @php
        $statusClass = match ($invoice->status) {
            'paid' => 'pill-paid',
            'partial' => 'pill-partial',
            'void' => 'pill-void',
            default => 'pill-unpaid',
        };
        $statusLabel = match ($invoice->status) {
            'paid' => 'Lunas',
            'partial' => 'Sebagian',
            'void' => 'Dibatalkan',
            default => 'Belum Lunas',
        };
        $documentId = sprintf('M2S-INV-%s-%s', $invoice->billingCycle?->due_date?->format('Ym') ?? now()->format('Ym'), $invoice->id);
    @endphp

    <div class="page">
        <div class="watermark"></div>

        @include('prints.partials.invoices.letterhead')

        <div class="title-block">
            <span class="badge">Tagihan Resmi</span>
            <h1>Tagihan Siswa</h1>
            <p>No Invoice: {{ $invoice->invoice_no }} | Periode: {{ $invoice->billingCycle?->period_label ?? '-' }}</p>
        </div>

        @include('prints.partials.invoices.meta-cards')
        @include('prints.partials.invoices.fee-breakdown')
        @include('prints.partials.invoices.payment-history')

        <div class="footer">
            <table>
                <tr>
                    <td>Generated by E-Keuangan MAN 2 Surakarta on {{ now()->format('Y-m-d H:i:s') }}</td>
                    <td class="center">Document ID: {{ $documentId }}</td>
                    <td class="right">Page {{ $loop->iteration }} of {{ $loop->count }}</td>
                </tr>
            </table>
        </div>
    </div>
    @endforeach
</body>
</html>
